#ifndef NETWORK_PROGRAMMING_SINGLE_THREAD_UDP_RECEIVER_H
#define NETWORK_PROGRAMMING_SINGLE_THREAD_UDP_RECEIVER_H

#include "common_net.h"

#define DEFAULT_PORT 6557

bool handle_mouse_position(SOCKET socket);
#endif //NETWORK_PROGRAMMING_SINGLE_THREAD_UDP_RECEIVER_H
