#ifndef NETWORK_PROGRAMMING_SINGLE_THREAD_UDP_RECEIVER_H
#define NETWORK_PROGRAMMING_SINGLE_THREAD_UDP_RECEIVER_H

#include "common_net.h"

#define DEFAULT_PORT 6557

bool process_receive_data(SOCKET socket);
#endif //NETWORK_PROGRAMMING_SINGLE_THREAD_UDP_RECEIVER_H
