#ifndef NETWORK_PROGRAMMING_SIMPLE_TCP_CLIENT_H
#define NETWORK_PROGRAMMING_SIMPLE_TCP_CLIENT_H

#include "common_net.h"
#include "shared_tcp_structs.h"
#endif //NETWORK_PROGRAMMING_SIMPLE_TCP_CLIENT_H
